import { Appointment } from "@/Types/AppointmentType";

export const historialSeed: Appointment[] = [
  {
    id: "c-001",
    matricula_paciente: "PAC-001",
    matricula_doctor: "DOC-001",
    nombre_paciente: "Juan García",
    fecha: "2025-01-15",
    estatus: "completada",
    diagnostico: "Hipertensión arterial leve",
    tratamiento: "Losartán 50mg cada 24 horas",
    medico_responsable: "Dr. Carlos Méndez",
    documents: []
  },
  {
    id: "c-002",
    matricula_paciente: "PAC-001",
    matricula_doctor: "DOC-002",
    nombre_paciente: "Juan García",
    fecha: "2025-03-02",
    estatus: "completada",
    diagnostico: "Infección respiratoria aguda",
    tratamiento: "Amoxicilina 500mg cada 8 horas por 7 días",
    medico_responsable: "Dra. Laura Ríos",
  },
  {
    id: "c-003",
    matricula_paciente: "PAC-001",
    matricula_doctor: "DOC-001",
    nombre_paciente: "Juan García",
    fecha: "2025-06-20",
    estatus: "completada",
    diagnostico: "Gastritis crónica",
    tratamiento: "Omeprazol 20mg en ayunas por 30 días",
    medico_responsable: "Dr. Carlos Méndez",
  },
  {
    id: "c-004",
    matricula_paciente: "PAC-002",
    matricula_doctor: "DOC-002",
    nombre_paciente: "María López",
    fecha: "2025-02-10",
    estatus: "completada",
    diagnostico: "Diabetes tipo 2",
    tratamiento: "Metformina 850mg con cada comida",
    medico_responsable: "Dra. Laura Ríos",
  },
  {
    id: "c-005",
    matricula_paciente: "PAC-002",
    matricula_doctor: "DOC-002",
    nombre_paciente: "María López",
    fecha: "2025-04-18",
    estatus: "completada",
    diagnostico: "Control glucémico",
    tratamiento: "Ajuste de dosis: Metformina 1000mg",
    medico_responsable: "Dra. Laura Ríos",
  },
  {
    id: "c-006",
    matricula_paciente: "PAC-002",
    matricula_doctor: "DOC-001",
    nombre_paciente: "María López",
    fecha: "2025-07-05",
    estatus: "completada",
    diagnostico: "Neuropatía diabética leve",
    tratamiento: "Vitamina B12 + control mensual",
    medico_responsable: "Dr. Carlos Méndez",
  },
];